### ISSUE TITLE
Issue when running "Get Store API0" - [ERROR] O Status Code recebido é direrente do esperado: 404

### ISSUE THREAD

**Issue by GusManley** [sprintermax/FNItemShopGenerator#1]
Getting Error "[ERROR] O Status Code recebido é direrente do esperado: 404" when trying to run "Get Store API0"

I have already made a .env file with the Authorization header

**Comment by sprintermax** [comment]
API 0 (Fortnite-api.com) code is outdated to handle the new store and items format returned from the api, I was already aware of it and will work on temporary fix when I have some free time
